version: "3"
services:
  cache:
    image: redis:5.0.6-alpine
    container_name: redis-interdisciplinaire
    expose:
      - "6379"
    volumes:
      - ./data/redis:/data
    entrypoint: redis-server --appendonly yes
    networks:
      interdisciplinaire:
        aliases:
          - redis
  db:
    image: mongo
    container_name: mongo-interdisciplinaire
    ports:
      - "27017:27017"
    volumes:
      - ./data/mongo:/data/db
    networks:
      interdisciplinaire:
        aliases:
          - database

  web:
    container_name: web-interdisciplinaire
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - db
      - cache
    links:
      - db:database
      - cache:redis
    command: >
      sh -c "pipenv install --system
             python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             gunicorn --bind 0.0.0.0:8000 interdisciplinaire.wsgi:application --worker-tmp-dir /dev/shm --workers=2 --thread=4 --worker-class=gthread  --reload"
    volumes:
      - .:/website
    environment:
      DB_IP: "database"
      DB_NAME: "interdisciplinaire"
      DB_USER: "interdisciplinaire"
      DB_PWD: "interdisciplinaire!pwd"
      CACHE_PWD: "interdisciplinaire!pwd"
      SECRET_KEY: "cléSecreteProjetInterdisciplinaire"
    networks:
      - interdisciplinaire

networks:
  interdisciplinaire:
    driver: bridge